#!/usr/bin/env python3
"""Generate the deterministic, non-speech WAV carrier used by fixture mode.

The generated media deliberately contains tone-coded intervals, not simulated human
speech. Its checked-in sidecar is suitable for exercising the product workflow, but
the fixture is excluded from ASR and product-quality claims.
"""

from __future__ import annotations

import argparse
import hashlib
import struct
from pathlib import Path


SAMPLE_RATE = 16_000
CHANNELS = 1
SAMPLE_WIDTH_BYTES = 2
DURATION_MS = 18_000
DEFAULT_OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "fixtures"
    / "media"
    / "pocket-demo-fixture.wav"
)

# Each interval is a stable machine-readable marker for one scripted sidecar turn.
# Integer frequencies and integer synthesis keep the result byte-for-byte portable.
TONE_INTERVALS: tuple[tuple[int, int, int], ...] = (
    (0, 4_000, 220),
    (4_000, 9_000, 277),
    (9_000, 14_000, 330),
    (14_000, 18_000, 392),
)


def _triangle(sample_index: int, frequency_hz: int, amplitude: int) -> int:
    """Return a triangle-wave sample using integer arithmetic only."""

    phase = (sample_index * frequency_hz * 4) % (SAMPLE_RATE * 4)
    quadrant, offset = divmod(phase, SAMPLE_RATE)
    slope = (2 * amplitude * offset) // SAMPLE_RATE
    if quadrant == 0:
        return slope
    if quadrant == 1:
        return (2 * amplitude) - slope
    if quadrant == 2:
        return -slope
    return (-2 * amplitude) + slope


def _carrier_sample(sample_index: int, frequency_hz: int, local_index: int, length: int) -> int:
    amplitude = 5_000
    primary = _triangle(sample_index, frequency_hz, amplitude)
    harmonic = _triangle(sample_index, frequency_hz * 2, amplitude // 3)
    value = (3 * primary + harmonic) // 4

    # A 10 ms linear fade avoids discontinuities at interval boundaries.
    fade_samples = SAMPLE_RATE // 100
    edge_distance = min(local_index, length - local_index - 1, fade_samples)
    gain_numerator = max(edge_distance, 0)
    return (value * gain_numerator) // fade_samples


def build_wav() -> bytes:
    total_samples = SAMPLE_RATE * DURATION_MS // 1_000
    samples = [0] * total_samples

    for start_ms, end_ms, frequency_hz in TONE_INTERVALS:
        start = SAMPLE_RATE * start_ms // 1_000
        end = SAMPLE_RATE * end_ms // 1_000
        length = end - start
        for index in range(start, end):
            samples[index] = _carrier_sample(
                index,
                frequency_hz,
                index - start,
                length,
            )

    pcm = struct.pack(f"<{len(samples)}h", *samples)
    byte_rate = SAMPLE_RATE * CHANNELS * SAMPLE_WIDTH_BYTES
    block_align = CHANNELS * SAMPLE_WIDTH_BYTES
    header = b"".join(
        (
            b"RIFF",
            struct.pack("<I", 36 + len(pcm)),
            b"WAVE",
            b"fmt ",
            struct.pack(
                "<IHHIIHH",
                16,
                1,
                CHANNELS,
                SAMPLE_RATE,
                byte_rate,
                block_align,
                SAMPLE_WIDTH_BYTES * 8,
            ),
            b"data",
            struct.pack("<I", len(pcm)),
        )
    )
    return header + pcm


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that the existing file exactly matches generated bytes",
    )
    parser.add_argument("--print-sha256", action="store_true")
    args = parser.parse_args()

    expected = build_wav()
    digest = hashlib.sha256(expected).hexdigest()

    if args.check:
        if not args.output.is_file():
            raise SystemExit(f"fixture is missing: {args.output}")
        actual = args.output.read_bytes()
        if actual != expected:
            actual_digest = hashlib.sha256(actual).hexdigest()
            raise SystemExit(
                f"fixture differs from generator: expected {digest}, got {actual_digest}"
            )
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(expected)

    if args.print_sha256:
        print(digest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
