"""baseline schema

Revision ID: c14c172f08b5
Revises:
Create Date: 2026-09-06
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c14c172f08b5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The production-shaped PostgreSQL image includes pgvector.  The current
    # lexical demo has no vector column yet, but owning the extension here keeps
    # fresh PostgreSQL deployments ready for a later typed-vector migration.
    # SQLite skips this branch entirely.
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_event",
        sa.Column("sequence", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("recording_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=96), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("sequence"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("domain_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_domain_event_recording_id"), ["recording_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_domain_event_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "idempotency_record",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=96), nullable=False),
        sa.Column("key", sa.String(length=180), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "operation", "key", name="uq_idempotency"),
    )
    with op.batch_alter_table("idempotency_record", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_idempotency_record_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "outbox_event",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_key", sa.String(length=180), nullable=False),
        sa.Column("event_type", sa.String(length=96), nullable=False),
        sa.Column("recording_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("deletion_generation", sa.Integer(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_key"),
    )
    with op.batch_alter_table("outbox_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_outbox_event_recording_id"), ["recording_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_outbox_event_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "principal",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "workspace",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("monthly_spend_limit_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ask_session",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("principal_id", sa.String(length=64), nullable=False),
        sa.Column("scope_type", sa.String(length=32), nullable=False),
        sa.Column("recording_ids", sa.JSON(), nullable=False),
        sa.Column("selection_segment_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ask_session", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ask_session_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "budget_reservation",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=160), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("recording_id", sa.String(length=36), nullable=True),
        sa.Column("ask_session_id", sa.String(length=36), nullable=True),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("reserved_usd", sa.Float(), nullable=False),
        sa.Column("committed_usd", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("release_reason", sa.String(length=160), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("budget_reservation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_budget_reservation_ask_session_id"), ["ask_session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_budget_reservation_attempt_id"), ["attempt_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_budget_reservation_recording_id"), ["recording_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_budget_reservation_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_budget_reservation_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "cost_event",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=160), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("recording_id", sa.String(length=36), nullable=True),
        sa.Column("ask_session_id", sa.String(length=36), nullable=True),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=96), nullable=False),
        sa.Column("model_alias", sa.String(length=96), nullable=False),
        sa.Column("resolved_model", sa.String(length=128), nullable=False),
        sa.Column("price_catalog_version", sa.String(length=64), nullable=False),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("reconciled_cost_usd", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("cache_reuse", sa.Boolean(), nullable=False),
        sa.Column("escalation_reason", sa.String(length=160), nullable=True),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id"),
    )
    with op.batch_alter_table("cost_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cost_event_recording_id"), ["recording_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cost_event_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "demo_session",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=128), nullable=False),
        sa.Column("principal_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("demo_session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_demo_session_token_hash"), ["token_hash"], unique=True)

    op.create_table(
        "membership",
        sa.Column("principal_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["principal_id"], ["principal.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("principal_id", "workspace_id"),
    )
    op.create_table(
        "recap",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("principal_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("project", sa.String(length=160), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("input_versions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recap", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recap_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "recording",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=240), nullable=False),
        sa.Column("original_filename", sa.String(length=240), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("requested_language", sa.String(length=32), nullable=False),
        sa.Column("requested_mode", sa.String(length=16), nullable=False),
        sa.Column("vocabulary_hints", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("folder", sa.String(length=160), nullable=True),
        sa.Column("summary_style", sa.String(length=32), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=48), nullable=False),
        sa.Column("error_code", sa.String(length=96), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("original_ready", sa.Boolean(), nullable=False),
        sa.Column("transcript_ready", sa.Boolean(), nullable=False),
        sa.Column("intelligence_ready", sa.Boolean(), nullable=False),
        sa.Column("indexed_ready", sa.Boolean(), nullable=False),
        sa.Column("deletion_generation", sa.Integer(), nullable=False),
        sa.Column("transcript_version", sa.Integer(), nullable=False),
        sa.Column("intelligence_version", sa.Integer(), nullable=False),
        sa.Column("etag_version", sa.Integer(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retention_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["principal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recording", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_recording_sha256"), ["sha256"], unique=False)
        batch_op.create_index(batch_op.f("ix_recording_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_recording_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "action_item",
        sa.Column("id", sa.String(length=220), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("recording_id", sa.String(length=36), nullable=False),
        sa.Column("intelligence_version", sa.Integer(), nullable=False),
        sa.Column("task", sa.Text(), nullable=False),
        sa.Column("owner_text", sa.String(length=160), nullable=True),
        sa.Column("due_text", sa.String(length=160), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("ambiguities", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recording.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("action_item", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_action_item_recording_id"), ["recording_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_action_item_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "ask_message",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ask_session_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("citations", sa.JSON(), nullable=False),
        sa.Column("abstained", sa.Boolean(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ask_session_id"], ["ask_session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ask_message", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ask_message_ask_session_id"), ["ask_session_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ask_message_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "evidence_unit",
        sa.Column("id", sa.String(length=220), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("recording_id", sa.String(length=36), nullable=False),
        sa.Column("transcript_version", sa.Integer(), nullable=False),
        sa.Column("deletion_generation", sa.Integer(), nullable=False),
        sa.Column("speaker_id", sa.String(length=64), nullable=True),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_normalized", sa.Text(), nullable=False),
        sa.Column("citation", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recording.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence_unit", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_unit_recording_id"), ["recording_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_evidence_unit_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "intelligence_version",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recording_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("transcript_version", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recording.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recording_id", "version", name="uq_intelligence_version"),
    )
    with op.batch_alter_table("intelligence_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_intelligence_version_recording_id"), ["recording_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_intelligence_version_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "media_grant",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("recording_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("deletion_generation", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recording.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("media_grant", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_media_grant_recording_id"), ["recording_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_media_grant_token_hash"), ["token_hash"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_media_grant_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "media_object",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recording_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("deletion_generation", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("blob_key", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recording.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blob_key"),
        sa.UniqueConstraint("recording_id", "kind", name="uq_media_kind"),
    )
    with op.batch_alter_table("media_object", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_media_object_recording_id"), ["recording_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_media_object_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "processing_run",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recording_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("deletion_generation", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("failure_code", sa.String(length=96), nullable=True),
        sa.Column("lease_owner", sa.String(length=160), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recording.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("processing_run", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_processing_run_lease_expires_at"), ["lease_expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_processing_run_lease_owner"), ["lease_owner"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_processing_run_recording_id"), ["recording_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_processing_run_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_processing_run_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "transcript_version",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recording_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=96), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("pipeline_version", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recording.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recording_id", "version", name="uq_transcript_version"),
    )
    with op.batch_alter_table("transcript_version", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transcript_version_recording_id"), ["recording_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transcript_version_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "upload_session",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recording_id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("deletion_generation", sa.Integer(), nullable=False),
        sa.Column("quarantine_key", sa.String(length=512), nullable=False),
        sa.Column("upload_token_hash", sa.String(length=64), nullable=False),
        sa.Column("expected_size", sa.Integer(), nullable=True),
        sa.Column("expected_sha256", sa.String(length=64), nullable=True),
        sa.Column("actual_size", sa.Integer(), nullable=True),
        sa.Column("actual_sha256", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recording.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspace.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quarantine_key"),
        sa.UniqueConstraint("recording_id"),
    )
    with op.batch_alter_table("upload_session", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_upload_session_upload_token_hash"), ["upload_token_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_upload_session_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "stage_run",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("processing_run_id", sa.String(length=36), nullable=False),
        sa.Column("recording_id", sa.String(length=36), nullable=False),
        sa.Column("stage", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["processing_run_id"],
            ["processing_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recording.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("processing_run_id", "stage", name="uq_run_stage"),
    )
    with op.batch_alter_table("stage_run", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stage_run_processing_run_id"), ["processing_run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stage_run_recording_id"), ["recording_id"], unique=False
        )

    op.create_table(
        "timeline_interval",
        sa.Column("id", sa.String(length=180), nullable=False),
        sa.Column("transcript_id", sa.String(length=36), nullable=False),
        sa.Column("recording_id", sa.String(length=36), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["transcript_id"], ["transcript_version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("timeline_interval", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_timeline_interval_recording_id"), ["recording_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_timeline_interval_transcript_id"), ["transcript_id"], unique=False
        )

    op.create_table(
        "transcript_segment",
        sa.Column("id", sa.String(length=180), nullable=False),
        sa.Column("transcript_id", sa.String(length=36), nullable=False),
        sa.Column("recording_id", sa.String(length=36), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("language_bcp47", sa.String(length=32), nullable=False),
        sa.Column("speaker_cluster_id", sa.String(length=64), nullable=True),
        sa.Column("speaker_display_name", sa.String(length=160), nullable=True),
        sa.Column("overlap_group_id", sa.String(length=64), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["transcript_id"], ["transcript_version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transcript_segment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transcript_segment_recording_id"), ["recording_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transcript_segment_transcript_id"), ["transcript_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transcript_segment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transcript_segment_transcript_id"))
        batch_op.drop_index(batch_op.f("ix_transcript_segment_recording_id"))

    op.drop_table("transcript_segment")
    with op.batch_alter_table("timeline_interval", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_timeline_interval_transcript_id"))
        batch_op.drop_index(batch_op.f("ix_timeline_interval_recording_id"))

    op.drop_table("timeline_interval")
    with op.batch_alter_table("stage_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stage_run_recording_id"))
        batch_op.drop_index(batch_op.f("ix_stage_run_processing_run_id"))

    op.drop_table("stage_run")
    with op.batch_alter_table("upload_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_upload_session_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_upload_session_upload_token_hash"))

    op.drop_table("upload_session")
    with op.batch_alter_table("transcript_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transcript_version_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_transcript_version_recording_id"))

    op.drop_table("transcript_version")
    with op.batch_alter_table("processing_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_processing_run_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_processing_run_status"))
        batch_op.drop_index(batch_op.f("ix_processing_run_recording_id"))
        batch_op.drop_index(batch_op.f("ix_processing_run_lease_owner"))
        batch_op.drop_index(batch_op.f("ix_processing_run_lease_expires_at"))

    op.drop_table("processing_run")
    with op.batch_alter_table("media_object", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_object_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_media_object_recording_id"))

    op.drop_table("media_object")
    with op.batch_alter_table("media_grant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_grant_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_media_grant_token_hash"))
        batch_op.drop_index(batch_op.f("ix_media_grant_recording_id"))

    op.drop_table("media_grant")
    with op.batch_alter_table("intelligence_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_intelligence_version_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_intelligence_version_recording_id"))

    op.drop_table("intelligence_version")
    with op.batch_alter_table("evidence_unit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_unit_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_unit_recording_id"))

    op.drop_table("evidence_unit")
    with op.batch_alter_table("ask_message", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ask_message_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_ask_message_ask_session_id"))

    op.drop_table("ask_message")
    with op.batch_alter_table("action_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_action_item_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_action_item_recording_id"))

    op.drop_table("action_item")
    with op.batch_alter_table("recording", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recording_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_recording_status"))
        batch_op.drop_index(batch_op.f("ix_recording_sha256"))

    op.drop_table("recording")
    with op.batch_alter_table("recap", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recap_workspace_id"))

    op.drop_table("recap")
    op.drop_table("membership")
    with op.batch_alter_table("demo_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_demo_session_token_hash"))

    op.drop_table("demo_session")
    with op.batch_alter_table("cost_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cost_event_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_cost_event_recording_id"))

    op.drop_table("cost_event")
    with op.batch_alter_table("budget_reservation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_budget_reservation_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_budget_reservation_status"))
        batch_op.drop_index(batch_op.f("ix_budget_reservation_recording_id"))
        batch_op.drop_index(batch_op.f("ix_budget_reservation_attempt_id"))
        batch_op.drop_index(batch_op.f("ix_budget_reservation_ask_session_id"))

    op.drop_table("budget_reservation")
    with op.batch_alter_table("ask_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ask_session_workspace_id"))

    op.drop_table("ask_session")
    op.drop_table("workspace")
    op.drop_table("principal")
    with op.batch_alter_table("outbox_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outbox_event_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_outbox_event_recording_id"))

    op.drop_table("outbox_event")
    with op.batch_alter_table("idempotency_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_idempotency_record_workspace_id"))

    op.drop_table("idempotency_record")
    with op.batch_alter_table("domain_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_domain_event_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_domain_event_recording_id"))

    op.drop_table("domain_event")
    # ### end Alembic commands ###
